//! Help-text rendering.
//! Matches Python Glances flag list per AC-14 (semantically equivalent).

pub fn print_help() {
    println!("glances-rs — pure-stdlib Rust port of Glances (system monitor)");
    println!();
    println!("Usage: glances-rs [OPTIONS]");
    println!();
    println!("Modes:");
    println!("  (default)               Terminal UI (removed; use -w)");
    println!("  -c, --client HOST       SNMP client (needs --snmp-force)");
    println!("  -w, --webserver         Run REST API + dashboard server");
    println!("  --stdout <spec>         Print specified stats to stdout");
    println!("  --stdout-csv            Stream CSV rows to stdout");
    println!("  --stdout-json           Stream JSON to stdout");
    println!("  --api-doc-restful       Print REST API documentation and exit");
    println!("  --api-doc, --api-restful-doc  Aliases for --api-doc-restful");
    println!("  --fetch, --stdout-fetch Fetch-like summary and exit");
    println!("  --modules-list          List plugins and exit");
    println!("  --issue                 Print debug/system info and exit");
    println!("  --ping ADDR             Probe a server's health endpoint and exit (HEALTHCHECK)");
    println!();
    println!("Display:");
    println!("  -t, --time SECONDS      Refresh interval (default 2)");
    println!("  -d, --debug             Enable debug logging");
    println!("  -q, --quiet             Suppress snapshot-loop output");
    println!("  --disable-history       Disable per-plugin history/sparklines");
    println!("  --disable-webui         Skip the WebUI (REST API only)");
    println!("  -2, --disable-left-sidebar  Hide left sidebar (network/diskio/fs/...)");
    println!("  -3, --disable-quicklook    Hide the quicklook gauges");
    println!("  -4, --full-quicklook       Quicklook + load only");
    println!("  -5, --disable-top          Hide the top menu (quicklook/cpu/mem/load)");
    println!("  --light, --enable-light    Light mode (no sidebar, processes, alerts, amps, containers, vms)");
    println!("  -0, --disable-irix      Divide task CPU by CPU count");
    println!();
    println!("Plugins:");
    println!("  --disable-plugin <list> Disable plugins (comma-separated, or all)");
    println!("  --enable-plugin <list>  Enable plugins (comma-separated)");
    println!("  --enable-irq            Enable the IRQ plugin");
    println!("  --disable-plugin-warn   Don't warn on plugin disable");
    println!("  --disable-process       Disable process modules");
    println!("  -f, --process-filter <regex> Only show processes matching regex");
    println!();
    println!("Network:");
    println!("  -B, --bind ADDR         Bind address (default 0.0.0.0)");
    println!("  --web-port PORT         Web server port (default 61208)");
    println!("  --access-log            Log every HTTP request (method, path, status)");
    println!("  --url-prefix PREFIX     URL prefix for REST API");
    println!();
    println!("Auth:");
    println!("  -u USER                 Auth username (forces password prompt on servers)");
    println!("  --username              Prompt for the username on stdin");
    println!("  --password              Prompt for the password on stdin (never via argv)");
    println!("  --auth-enabled          Enable JWT authentication");
    println!("  --secure-config PATH    Path to password hash file");
    println!();
    println!("Misc:");
    println!("  -C, --config PATH       Override config file location");
    println!("  -P, --plugins PATH      Additional plugin directory");
    println!("  --stop-after N          Exit after N refresh cycles");
    println!("  --open-web-browser      Open the Web UI in the default browser");
    println!("  --enable-mcp            Enable MCP server alongside web server");
    println!("  --fetch-template PATH   Override the fetch summary template");
    println!("  --disable-config-exec   Disable `cmd` execution in config file");
    println!("  --disable-check-update  Skip update check at startup");
    println!("  --memory-leak           Enable memory-leak debug helper");
    println!("  --trace-malloc          Trace memory allocations");
    println!();
    println!("MCP:");
    println!("  --mcp-path PATH         Mount path for MCP server (default /mcp)");
    println!();
    println!("SNMP:");
    println!("  --snmp-community STR    SNMP community string");
    println!("  --snmp-port PORT        SNMP port (default 161)");
    println!("  --snmp-version VER      SNMP version: 1, 2c, or 3 (default 2c)");
    println!("  --snmp-user USER        SNMPv3 username");
    println!("  --snmp-auth KEY         SNMPv3 auth key");
    println!("  --snmp-force            Force SNMP mode");
    println!();
    println!("Other:");
    println!("  -h, --help              Show this help message");
    println!("  -V, --version           Show version");
    println!();
    println!("See docs/CLI.md for the full flag reference and PLAN.md for the");
    println!("implementation roadmap. Project: pure std + core + alloc + libc only.");
}
