//! Help-text rendering.
//! Matches Python Glances flag list per AC-14 (semantically equivalent).

pub fn print_help() {
    println!("glances-rs — pure-stdlib Rust port of Glances (system monitor)");
    println!();
    println!("Usage: glances-rs [OPTIONS]");
    println!();
    println!("Modes:");
    println!("  (default)               Standalone curses TUI");
    println!("  -s, --server            Run as XML-RPC server");
    println!("  -c, --client HOST       Run as XML-RPC client");
    println!("  -w, --webserver         Run REST API + Vue UI server");
    println!("  --browser               Curses browser for remote servers");
    println!("  --stdout <spec>         Print specified stats to stdout");
    println!("  --stdout-csv            Stream CSV rows to stdout");
    println!("  --stdout-json           Stream JSON to stdout");
    println!("  --api-doc-restful       Print REST API documentation and exit");
    println!("  --api-doc, --api-restful-doc  Aliases for --api-doc-restful");
    println!("  --fetch, --stdout-fetch Fetch-like summary and exit");
    println!("  --modules-list          List plugins and exporters and exit");
    println!("  --issue                 Print debug/system info and exit");
    println!();
    println!("Display:");
    println!("  -t, --time SECONDS      Refresh interval (default 2)");
    println!("  -d, --debug             Enable debug logging");
    println!("  -q, --quiet             Disable the curses UI");
    println!("  --disable-history       Disable per-plugin history/sparklines");
    println!("  --disable-webui         Skip the WebUI (REST API only)");
    println!("  --light, -2, -3, -4, -5 Light mode (disable some plugins)");
    println!("  -1, --percpu            Start in per-CPU mode");
    println!("  -0, --disable-irix      Divide task CPU by CPU count");
    println!("  -6, --meangpu           Start in mean GPU mode");
    println!("  -b, --byte              Network rate in bytes per second");
    println!("  --fahrenheit            Temperatures in Fahrenheit");
    println!("  --sparkline             Sparklines instead of bars");
    println!("  --disable-bold          Disable bold in the terminal");
    println!("  --disable-bg            Disable background colors");
    println!("  --disable-separator     Disable UI separators");
    println!("  --disable-cursor        Disable process selection cursor");
    println!("  --disable-unicode       Disable unicode characters");
    println!("  --programs, --program   Accumulate processes by program");
    println!("  --sort-processes KEY    Sort process list by KEY");
    println!("  --arrow-keys-sort       Arrow keys sort the process list");
    println!("  --process-focus LIST    Focus on comma-separated filters");
    println!("  --process-short-name    Short process names (default)");
    println!("  --process-long-name     Long process names");
    println!("  --hide-kernel-threads   Hide kernel threads");
    println!("  --enable-process-extended Extended stats on top process");
    println!("  --hide-public-info      Hide public info (e.g. public IP)");
    println!("  --diskio-iops           Show IO per second in DiskIO");
    println!("  --diskio-latency        Show IO latency in DiskIO");
    println!("  --diskio-show-ramfs     Show RAM filesystems in DiskIO");
    println!("  --strftime FMT          Date format for standalone mode");
    println!();
    println!("Plugins:");
    println!("  --disable-plugin <list> Disable plugins (comma-separated, or all)");
    println!("  --enable-plugin <list>  Enable plugins (comma-separated)");
    println!("  --enable-irq            Enable the IRQ plugin");
    println!("  --disable-plugin-warn   Don't warn on plugin disable");
    println!("  --disable-process       Disable process modules");
    println!("  -f, --process-filter <regex> Only show processes matching regex");
    println!("  --fs-free-space         Display filesystem free space instead of used");
    println!();
    println!("Network:");
    println!("  -B, --bind ADDR         Bind address (default 0.0.0.0)");
    println!("  -p, --port PORT         XML-RPC port (default 61209)");
    println!("  --web-port PORT         Web server port (default 61208)");
    println!("  --url-prefix PREFIX     URL prefix for REST API");
    println!("  --cached-time SECONDS   Server-side cache TTL (default 1)");
    println!();
    println!("Auth:");
    println!("  -u, --username USER     Auth username");
    println!("  --password              Prompt for password");
    println!("  --auth-enabled          Enable JWT authentication");
    println!("  --secure-config PATH    Path to password hash file");
    println!();
    println!("Export:");
    println!("  --export <targets>      Enable exporters (comma-separated list)");
    println!("  --export-csv-file PATH  CSV exporter output file");
    println!("  --export-csv-overwrite  Overwrite CSV file instead of appending");
    println!("  --export-json-file PATH JSON exporter output file");
    println!("  --export-graph-path DIR Graph (SVG) exporter folder");
    println!("  --export-process-filter REGEX Export-side process filter");
    println!("  --export-<name>-<opt>   Per-exporter options (host, port, ...)");
    println!();
    println!("Misc:");
    println!("  -C, --config PATH       Override config file location");
    println!("  -P, --plugins PATH      Additional plugin directory");
    println!("  --stop-after N          Exit after N refresh cycles");
    println!("  --open-web-browser      Open the Web UI in the default browser");
    println!("  --enable-mcp            Enable MCP server alongside web server");
    println!("  --fetch-template PATH   Override the fetch summary template");
    println!("  --disable-autodiscover  Disable server autodiscovery");
    println!("  --disable-config-exec   Disable `cmd` execution in config file");
    println!("  --disable-check-update  Skip update check at startup");
    println!("  --memory-leak           Enable memory-leak debug helper");
    println!("  --trace-malloc          Trace memory allocations");
    println!();
    println!("MCP:");
    println!("  --mcp-path PATH         Mount path for MCP server (default /mcp)");
    println!();
    println!("SNMP:");
    println!("  --snmp-community STR    SNMP community string");
    println!("  --snmp-port PORT        SNMP port (default 161)");
    println!("  --snmp-version VER      SNMP version: 1, 2c, or 3 (default 2c)");
    println!("  --snmp-user USER        SNMPv3 username");
    println!("  --snmp-auth KEY         SNMPv3 auth key");
    println!("  --snmp-force            Force SNMP mode");
    println!();
    println!("Other:");
    println!("  -h, --help              Show this help message");
    println!("  -V, --version           Show version");
    println!();
    println!("See docs/CLI.md for the full flag reference and PLAN.md for the");
    println!("implementation roadmap. Project: pure std + core + alloc + libc only.");
}
